spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

storage:
  local:
    post-image-path: ${POST_IMAGE_STORAGE_PATH}
  post-image-public-url-prefix: ${POST_IMAGE_PUBLIC_URL_PREFIX}

audit:
  service:
    url: ${AUDIT_SERVICE_URL}
  internal:
    secret: ${AUDIT_INTERNAL_SECRET}
